### ISSUE TITLE
Webcrawler

### ISSUE THREAD

**Issue by SairanSerra** [SairanSerra/SafeNature-API-TCC#2]
Deve ser feito um Webcrawler para popular as bases com informações de desastres naturais.

### Critérios de Aceite
- Deve salvar as informações nos bancos de dados
- Os dados salvos devem ser atualizados a cada 5 minutos no banco de dados
- Deve ser salvo na seguinte estrutura de banco de dados
![Image](https://github.com/user-attachments/assets/82014d6e-4fa8-45b7-9a73-011587be2c0a)

### Definição de pronto
- Ter os diagramas e documentação adequada da funcionalidade
- Está de acordo com os princípios de Clean Architeture
- Estar de acordo com os princípios de Clean Architeture

Estrutura do banco de dados das informações que serão adicionadas e atualizadas

**Comment by davifma** [comment]
Critério de Aceite
 - Diferente em cada tarefa

Definição de pronto (O mesmo pra tudo)
 - Ter os diagramas e documentação adequada da funcionalidade
 - Está de acordo com os princípios de Clean Architeture
 - Estar de acordo com os princípios de Clean Architeture

**Comment by SairanSerra** [comment]
Atualizado a Documentação incluindo schema de banco

**Comment by davifma** [comment]
Onde está a documentação e os schemas? Deixa o link nos comentários também. E como eu posso testar o Webcrawler ?
