### ISSUE TITLE
Lista de desastres naturais

### ISSUE THREAD

**Issue by SairanSerra** [SairanSerra/SafeNature-API-TCC#3]
Deve ser criado um endpoint que traga a lista de todos os desastres naturais.

O intuito é para mostrar ao usuário todos os possíveis desastres próximos.

### Critérios de Aceite
- Deve conter todos os desastres naturais atualizados
- Os dados são a O desastre que está ocorrendo em conjunto com o lat long
- Deve trazer a listagem de todos os desastres

### Definição de pronto
Ter os diagramas e documentação adequada da funcionalidade
Está de acordo com os princípios de Clean Architeture
Estar de acordo com os princípios de Clean Architeture

**Comment by davifma** [comment]
Quais são os dados  dos desastres que devem ser atualizados?

**Comment by SairanSerra** [comment]
> Quais são os dados dos desastres que devem ser atualizados?

A listagem de localização e qual desastre está ocorrendo no local

**Comment by davifma** [comment]
E onde está essa listagem? Quais são os dados?
